package codegen

import (
	"fmt"
	"strings"
)

// GenerateTypeScript generates TypeScript type definitions and React hooks from ScanResult.
func GenerateTypeScript(scan *ScanResult) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by Zyra Codegen. DO NOT EDIT.\n")
	sb.WriteString("// Single source of truth defined in Go structs.\n\n")
	sb.WriteString("import { useAction } from \"@zyra/client\";\n\n")

	// Generate interfaces for Go structs
	for _, st := range scan.Structs {
		sb.WriteString(fmt.Sprintf("export interface %s {\n", st.Name))
		for _, field := range st.Fields {
			tsType := mapGoTypeToTS(field.Type)
			sb.WriteString(fmt.Sprintf("  %s: %s;\n", field.JSONName, tsType))
		}
		sb.WriteString("}\n\n")
	}

	// Generate RPC Action Hooks
	for _, action := range scan.Actions {
		hookName := "use" + action.Name
		endpoint := fmt.Sprintf("/_zyra/action/%s/%s", action.Package, action.Name)

		inType := mapGoTypeToTS(action.InputType)
		outType := mapGoTypeToTS(action.OutputType)

		sb.WriteString(fmt.Sprintf("export function %s() {\n", hookName))
		sb.WriteString(fmt.Sprintf("  return useAction<%s, %s>(\"%s\");\n", inType, outType, endpoint))
		sb.WriteString("}\n\n")
	}

	return sb.String()
}

func mapGoTypeToTS(goType string) string {
	if strings.HasPrefix(goType, "[]") {
		elem := mapGoTypeToTS(strings.TrimPrefix(goType, "[]"))
		return elem + "[]"
	}
	if strings.HasPrefix(goType, "map[") {
		return "Record<string, any>"
	}

	switch goType {
	case "string":
		return "string"
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
		return "number"
	case "bool":
		return "boolean"
	case "void":
		return "void"
	case "any", "interface{}":
		return "any"
	default:
		// If custom struct or selector type
		if idx := strings.LastIndex(goType, "."); idx != -1 {
			return goType[idx+1:]
		}
		return goType
	}
}
